# Generated by Django 5.1.1 on 2024-10-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_alter_reservation_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='date',
            new_name='dateOfDeparture',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='time',
            new_name='estimatedTimeOfDeparture',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airline',
            new_name='operatingAirlines',
        ),
    ]
